# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuWindow(object):
    def setupUi(self, MenuWindow):
        MenuWindow.setObjectName("MenuWindow")
        MenuWindow.resize(236, 310)
        MenuWindow.setMaximumSize(QtCore.QSize(240, 320))
        self.centralwidget = QtWidgets.QWidget(MenuWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.b_retail = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b_retail.setFont(font)
        self.b_retail.setStyleSheet("background-color: rgb(205, 255, 218);")
        self.b_retail.setObjectName("b_retail")
        self.verticalLayout.addWidget(self.b_retail)
        self.b_epp = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b_epp.setFont(font)
        self.b_epp.setStyleSheet("background-color: rgb(205, 255, 218);")
        self.b_epp.setObjectName("b_epp")
        self.verticalLayout.addWidget(self.b_epp)
        self.b_mask = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b_mask.setFont(font)
        self.b_mask.setStyleSheet("background-color: rgb(205, 255, 218);")
        self.b_mask.setObjectName("b_mask")
        self.verticalLayout.addWidget(self.b_mask)
        self.b_load = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b_load.setFont(font)
        self.b_load.setStyleSheet("background-color: rgb(205, 255, 218);")
        self.b_load.setObjectName("b_load")
        self.verticalLayout.addWidget(self.b_load)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        MenuWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MenuWindow)
        QtCore.QMetaObject.connectSlotsByName(MenuWindow)

    def retranslateUi(self, MenuWindow):
        _translate = QtCore.QCoreApplication.translate
        MenuWindow.setWindowTitle(_translate("MenuWindow", "Menu"))
        self.b_retail.setText(_translate("MenuWindow", "Retail"))
        self.b_epp.setText(_translate("MenuWindow", "EPP"))
        self.b_mask.setText(_translate("MenuWindow", "Mask"))
        self.b_load.setText(_translate("MenuWindow", "Cargar modelo"))
        self.label.setText(_translate("MenuWindow", "-"))
